[PACKAGE]
NAME = "COMPILER"
VERSION = "0.1.0"
EDITION = "2021"


[PACKAGE.METADATA.SCRIPTS]
RUN_M1 = "CARGO RUN --BIN M1"
RUN_M2 = "CARGO RUN --BIN M2"
RUN_M3 = "CARGO RUN --BIN M3"

[[BIN]]
NAME = "ALGO1"
PATH = "ALGORITHM1.RS"

[[bin]]
name = "algo2"
path = "algorithm2.rs"
[[bin]]
name = "algo3"
path = "algorithm3.rs"
[[bin]]
name = "algo4"
path = "algorithm4.rs"
[[bin]]
name = "algo5"
path = "algorithm5.rs"
